### ISSUE TITLE
Parameter specified as non-null is null: method com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke

### ISSUE THREAD

**Issue by ColtonIdle** [airbnb/epoxy#1001]
Noticed this during normal compilation (hitting run in Android Studio)

```
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke, parameter it
	at com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke(Logger.kt)
	at com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke(Logger.kt)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:71)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2519)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2536)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2535)
	at com.airbnb.epoxy.processor.LoggerKt.joinToString(Logger.kt:109)
	at com.airbnb.epoxy.processor.LoggerKt.access$joinToString(Logger.kt:1)
	at com.airbnb.epoxy.processor.Timing.toString(Logger.kt:124)
	at com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke(Logger.kt:109)
	at com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke(Logger.kt)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:71)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2519)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2536)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2535)
	at com.airbnb.epoxy.processor.LoggerKt.joinToString(Logger.kt:109)
	at com.airbnb.epoxy.processor.LoggerKt.access$joinToString(Logger.kt:1)
	at com.airbnb.epoxy.processor.Timing.toString(Logger.kt:124)
	at com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke(Logger.kt:109)
	at com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke(Logger.kt)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:71)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2519)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2536)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2535)
	at com.airbnb.epoxy.processor.LoggerKt.joinToString(Logger.kt:109)
	at com.airbnb.epoxy.processor.LoggerKt.access$joinToString(Logger.kt:1)
	at com.airbnb.epoxy.processor.Timing.toString(Logger.kt:124)
	at com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke(Logger.kt:109)
	at com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke(Logger.kt)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:71)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2519)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2536)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2535)
	at com.airbnb.epoxy.processor.LoggerKt.joinToString(Logger.kt:109)
	at com.airbnb.epoxy.processor.LoggerKt.access$joinToString(Logger.kt:1)
	at com.airbnb.epoxy.processor.Timing.toString(Logger.kt:124)
	at com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke(Logger.kt:109)
	at com.airbnb.epoxy.processor.LoggerKt$joinToString$1.invoke(Logger.kt)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:71)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2519)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2536)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2535)
	at com.airbnb.epoxy.processor.LoggerKt.joinToString(Logger.kt:109)
	at com.airbnb.epoxy.processor.LoggerKt.access$joinToString(Logger.kt:1)
	at com.airbnb.epoxy.processor.Logger.printTimings(Logger.kt:101)
	at com.airbnb.epoxy.processor.BaseProcessor$process$1.invokeSuspend(BaseProcessor.kt:150)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

after I reran it it worked. Figured I'd file just in case.

**Comment by elihart** [comment]
Thanks for reporting, it looks like you have the options for both parallel processing and log timings enabled? Can  you share the details from the timing log output? Can you confirm which version you're on?

**Comment by ColtonIdle** [comment]
>looks like you have the options for both parallel processing and log timings enabled
```
        buildType.javaCompileOptions.annotationProcessorOptions.arguments =
                [
                        requireHashCodeInEpoxyModels : "false",
                        requireAbstractEpoxyModels   : "true",
                        implicitlyAddAutoModels      : "true",
                        logEpoxyTimings              : "true",
                        enableParallelEpoxyProcessing: "true"
                ]
```
>Can you share the details from the timing log output?
It doesn't look like it printed? Seems like it crashed if I'm understanding the trace correctly.

>Can you confirm which version you're on?
4.0.0-beta4

**Comment by elihart** [comment]
yes, i mean the log timings of the build when it doesn't crash. lmk if it happens more than that one time (or roughly how often it occurs or how rare it is)

**Comment by ColtonIdle** [comment]
Here is a sample of the timings when everything works. I would say at this point it works like 95% of the time. I have seen it fail locally and on CI with the same error.

```
warning: EpoxyProcessor completed in 1611 ms:
    Process Round: 1: 1243 ms 
      Process package configurations: 81 ms 
      get annotations: EpoxyAttribute: 70 ms 
      Find EpoxyAttribute class: 172 ms (223 items in parallel)
      Build EpoxyAttribute: 195 ms (223 items in parallel)
      get annotations: EpoxyModelClass: 88 ms 
      Process EpoxyModelClass: 55 ms (56 items in parallel)
      addAttributesFromOtherModules: 17 ms (56 items in parallel)
      updateClassesForInheritance: 9 ms (56 items in parallel)
      Check for styleable: 11 ms (56 items in parallel)
      Write model: 363 ms (56 items in parallel)
    Process Round: 2: 3 ms 
      get annotations: EpoxyAttribute: 1 ms 
      get annotations: EpoxyModelClass: 1 ms 
    validateAttributesImplementHashCode: 11 ms 
      validateAttributeInfo: 5 ms (223 items in parallel)
    generateKotlinExtensions: 354 ms 
      generateExtensionsForModels: 95 ms (27 items in parallel)
        buildExtensionFile: 53 ms (1 items in parallel)
          buildExtensionFile: 56 ms (6 items in parallel)
            buildExtensionFile: 41 ms (1 items in parallel)
              buildExtensionFile: 39 ms (7 items in parallel)
        buildExtensionFile: 16 ms (6 items in parallel)
          buildExtensionFile: 10 ms (1 items in parallel)
            buildExtensionFile: 1 ms (6 items in parallel)
            buildExtensionFile: 14 ms (6 items in parallel)
      writeExtensionsForModels: 245 ms (27 items )
```

**Comment by elihart** [comment]
thanks, do you have databinding  processor timings  as well?  This is only the Epoxy model processor.

for now i would recommend disabling timings if it is failing for you. generally  it should only be turned of for specific debugging instances, not all the time

**Comment by ColtonIdle** [comment]
databinding? I don't use databinding. I do use viewbinding though.

**Comment by elihart** [comment]
I think this will be fixed with https://github.com/airbnb/epoxy/pull/1016
