### ISSUE TITLE
Tests in epoxy-integrationtest are flaky

### ISSUE THREAD

**Issue by pmecho** [airbnb/epoxy#1050]
While working on a PR I had a failure running `./gradlew check`. I thought this might be related to my bumping of `androidx.test:core` to `1.3` but I also get the same flakiness on `1.2`. One example is that they were successful 3 times in a row and the 4th time is when they failed.

One stacktrace is:
```
java.lang.NullPointerException
	at com.airbnb.epoxy.integrationtest.KotlinViewWithDefaultParamsModel_.bind(KotlinViewWithDefaultParamsModel_.java:104)
	at com.airbnb.epoxy.integrationtest.KotlinViewWithDefaultParamsModel_.bind(KotlinViewWithDefaultParamsModel_.java:33)
	at com.airbnb.epoxy.EpoxyViewHolder.bind(EpoxyViewHolder.java:43)
	at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:118)
	at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:106)
	at com.airbnb.epoxy.ControllerLifecycleHelper.bindModels(ControllerLifecycleHelper.java:30)
	at com.airbnb.epoxy.ControllerLifecycleHelper.bindModels(ControllerLifecycleHelper.java:23)
	at com.airbnb.epoxy.ControllerLifecycleHelper.buildModelsAndBind(ControllerLifecycleHelper.java:19)
	at com.airbnb.epoxy.KotlinDefaultParamTest$TestController.buildWithModel(KotlinDefaultParamTest.kt:36)
	at com.airbnb.epoxy.KotlinDefaultParamTest.defaultParamIsUsed(KotlinDefaultParamTest.kt:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Gist of full failures: https://gist.github.com/pmecho/3f570db0c7aea6af0d60a03e27446091

**Comment by elihart** [comment]
Thanks for reporting, I saw this too, but thought I fixed it :( I think it started after bumping some dependency, potentially robolectric to 4.4

i'm not going to prioritize for now as it passes most of the time, but need to get to it at some point.

**Comment by elihart** [comment]
fixed in https://github.com/airbnb/epoxy/pull/1055
