### ISSUE TITLE
ConcurrentModificationException when building with enableParallelEpoxyProcessing

### ISSUE THREAD

**Issue by blazeroni** [airbnb/epoxy#1065]
Running epoxy 4.1.0 on Kotlin 4.10.0 with `enableParallelEpoxyProcessing` enabled.  Build randomly failed with the message below.  Haven't seen similar errors with `enableParallelEpoxyProcessing` disabled, though admittedly I haven't built that many times with the new library version yet.

```
error: EpoxyProcessorException: resolveDataBindingClassesAndWriteJava failed
  com.airbnb.epoxy.processor.EpoxyProcessorException: resolveDataBindingClassesAndWriteJava failed
        at com.airbnb.epoxy.processor.Logger.logError(Logger.kt:63)
        at com.airbnb.epoxy.processor.Asyncable$DefaultImpls.awaitAndLog(Asyncable.kt:136)
        at com.airbnb.epoxy.processor.Asyncable$awaitAndLog$1.invokeSuspend(Asyncable.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
  Caused by: java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
        at jdk.compiler/com.sun.tools.javac.code.Symtab.doEnterClass(Symtab.java:721)
        at jdk.compiler/com.sun.tools.javac.code.Symtab.enterClass(Symtab.java:735)
        at jdk.compiler/com.sun.tools.javac.code.ClassFinder.loadClass(ClassFinder.java:429)
        at jdk.compiler/com.sun.tools.javac.comp.Resolve.loadClass(Resolve.java:1996)
        at jdk.compiler/com.sun.tools.javac.comp.Resolve.findIdentInPackageInternal(Resolve.java:2386)
        at jdk.compiler/com.sun.tools.javac.comp.Resolve.findIdentInPackage(Resolve.java:2374)
        at jdk.compiler/com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:363)
        at jdk.compiler/com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:354)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2122)
        at jdk.compiler/com.sun.source.util.SimpleTreeVisitor.visit(SimpleTreeVisitor.java:80)
        at jdk.compiler/com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:357)
        at jdk.compiler/com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:354)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2122)
        at jdk.compiler/com.sun.tools.javac.comp.Attr.attribIdent(Attr.java:350)
        at jdk.compiler/com.sun.tools.javac.comp.Attr.attribIdent(Attr.java:342)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.resolveIdent(JavaCompiler.java:743)
        at jdk.compiler/com.sun.tools.javac.model.JavacElements.nameToSymbol(JavacElements.java:254)
        at jdk.compiler/com.sun.tools.javac.model.JavacElements.unboundNameToSymbol(JavacElements.java:196)
        at jdk.compiler/com.sun.tools.javac.model.JavacElements.doGetElement(JavacElements.java:182)
        at jdk.compiler/com.sun.tools.javac.model.JavacElements.doGetTypeElement(JavacElements.java:172)
        at jdk.compiler/com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:160)
        at jdk.compiler/com.sun.tools.javac.model.JavacElements.getTypeElement(JavacElements.java:87)
        at com.airbnb.epoxy.processor.KotlinUtilsKt.getTypeMirrorNullable(KotlinUtils.kt:62)
        at com.airbnb.epoxy.processor.Utils.areParamsTheSame(Utils.kt:323)
        at com.airbnb.epoxy.processor.Utils.getMethodOnClass(Utils.kt:290)
        at com.airbnb.epoxy.processor.Utils.implementsMethod(Utils.kt:266)
        at com.airbnb.epoxy.processor.GeneratedModelWriter.generateDataBindingMethodsIfNeeded(GeneratedModelWriter.kt:1191)
        at com.airbnb.epoxy.processor.GeneratedModelWriter.generateClassForModel(GeneratedModelWriter.kt:150)
        at com.airbnb.epoxy.processor.GeneratedModelWriter.generateClassForModel$default(GeneratedModelWriter.kt:121)
        at com.airbnb.epoxy.processor.DataBindingProcessor$resolveDataBindingClassesAndWriteJava$2.invokeSuspend(DataBindingProcessor.kt:117)
        at com.airbnb.epoxy.processor.DataBindingProcessor$resolveDataBindingClassesAndWriteJava$2.invoke(DataBindingProcessor.kt)
        at com.airbnb.epoxy.processor.Asyncable$filter$2$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(Asyncable.kt:77)
        ... 6 more
```

**Comment by elihart** [comment]
Thanks for reporting, it should go away if you disable parallel processing, but please let me know if it doesn't.

It looks like it is happening with databinding layouts. We don't use those ourselves, which helps explain why we have never run into this. I will look into and fix it.
