### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hm-tamim** [airbnb/epoxy#1121]
Randomly getting this error on Crashlytics. Hard to recreate the same error. I made sure, all the items have unique ids.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 13
       at java.util.Arrays.rangeCheck(Arrays.java:123)
       at java.util.Arrays.fill(Arrays.java:2831)
       at androidx.recyclerview.widget.StaggeredGridLayoutManager$LazySpanLookup.invalidateAfter(StaggeredGridLayoutManager.java:2876)
       at androidx.recyclerview.widget.StaggeredGridLayoutManager.handleUpdate(StaggeredGridLayoutManager.java:1548)
       at androidx.recyclerview.widget.StaggeredGridLayoutManager.onItemsUpdated(StaggeredGridLayoutManager.java:1524)
       at androidx.recyclerview.widget.RecyclerView$6.dispatchUpdate(RecyclerView.java:1021)
       at androidx.recyclerview.widget.RecyclerView$6.onDispatchSecondPass(RecyclerView.java:1032)
       at androidx.recyclerview.widget.AdapterHelper.consumePostponedUpdates(AdapterHelper.java:121)
       at androidx.recyclerview.widget.AdapterHelper.consumeUpdatesInOnePass(AdapterHelper.java:557)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4128)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
       at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
       at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
       at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1996)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1842)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1686)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1595)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
       at com.android.internal.policy.DecorView.onLayout(DecorView.java:902)
       at android.view.View.layout(View.java:20948)
       at android.view.ViewGroup.layout(ViewGroup.java:6279)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3037)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2545)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
       at android.view.Choreographer.doCallbacks(Choreographer.java:893)
       at android.view.Choreographer.doFrame(Choreographer.java:812)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by elihart** [comment]
Do you have any evidence that this is related to Epoxy? Seems more likely to be a StaggeredGridLayoutManager bug

**Comment by hm-tamim** [comment]
This issue got resolved by using `controller.requestDelayedModelBuild(100)` instead of `controller.requestModelBuild();`

Our app was calling requestModelBuild from 8+ observers, as there are lots of carousel. 

Added this method to generate random int for delayMs, like this `requestDelayedModelBuild(randInt(100, 200))`. No crashes so far.
```
public static int randInt(int min, int max) {
        Random rand = new Random();
        return rand.nextInt((max - min) + 1) + min;
    }
```
