### ISSUE TITLE
ConcurrentModificationException error from Epoxy Controller

### ISSUE THREAD

**Issue by hm-tamim** [airbnb/epoxy#1132]
Getting this error, we are using epoxy 4.3.1 and recyclerView 1.2.0-beta01

```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at bd.com.evaly.evalyshop.ui.campaign.controller.CampaignController.buildModels(CampaignController.java:135)
       at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:281)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

Code (CampaignController.java:135):

```
for (CampaignProductResponse item : productList) {
}
```

**Comment by elihart** [comment]
you need to synchronize your code

**Comment by MoneyQianN** [comment]
You could use TypedEpoxyController<yourCustomState>,and use setData(new state) to fix it .
method setData() would lock update method when requestModeBuild() work
