### ISSUE TITLE
getting crash with java.lang.AbstractMethodError after update from version 4.20 to 4.4.0

### ISSUE THREAD

**Issue by van-dn** [airbnb/epoxy#1140]
Getting a crash when update from version 4.2.0 to 4.4.0. Please help me check. 
Here is the log crash:
```
Fatal Exception: java.lang.AbstractMethodError: abstract method "com.airbnb.epoxy.rcom.airbnb.epoxy.v.X7(android.view.ViewParent)"
       at com.airbnb.epoxy.EpoxyViewHolder.bind(EpoxyViewHolder.java:51)
       at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:118)
       at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:20)
       at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
       at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
       at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
       at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
       at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
       at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
       at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
       at android.view.View.measure(View.java:24939)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7132)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:24939)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7132)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:24939)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7132)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:24939)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7132)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:24939)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
       at android.view.View.measure(View.java:24939)
       at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1599)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:585)
       at android.view.View.measure(View.java:24939)
       at com.sample.app.smartrefresh.SmartRefreshLayout.onMeasure(SmartRefreshLayout.java:634)
       at android.view.View.measure(View.java:24939)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
       at android.view.View.measure(View.java:24939)
       at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1638)
       at android.view.View.measure(View.java:24939)
       at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:719)
       at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:399)
       at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:315)
       at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:113)
       at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1465)
       at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1540)
       at android.view.View.measure(View.java:24939)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7132)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
       at android.view.View.measure(View.java:24939)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7132)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:24939)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7132)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:24939)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7132)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
       at android.view.View.measure(View.java:24939)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7132)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:993)
       at android.view.View.measure(View.java:24939)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3286)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2013)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2315)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1873)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8478)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by elihart** [comment]
looks like the method name is obfuscated on your end so I can't tell what it is calling

**Comment by van-dn** [comment]
@elihart the crash happen when use expoxy with databinding

`Method com.airbnb.epoxy.DataBindingEpoxyModel$DataBindingHolder net.module.ecart.InstoreShoppingScanEntryBindingModel_.createNewHolder(android.view.ViewParent) overrides final method in class Lcom/airbnb/epoxy/DataBindingEpoxyModel; (declaration of 'net.vinid.module.ecart.InstoreShoppingScanEntryBindingModel_' appears in /data/app/net.vinid.module.ecart.sample.dev-vkFXDsOyZkJ--863DR4TKg==/base.apk!classes49.dex)`
