### ISSUE TITLE
EpoxyProcessorException: Write model failed Caused by: java.lang.IllegalStateException: Type mirror does not exist for android.view.ViewParent

### ISSUE THREAD

**Issue by apramana** [airbnb/epoxy#1145]
Intermittently getting the following error during kapt since updating to 4.4.1 (previously worked fine in 4.2.0):

```
error: EpoxyProcessorException: Write model failed
  com.airbnb.epoxy.processor.EpoxyProcessorException: Write model failed
  	at com.airbnb.epoxy.processor.Logger.logError(Logger.kt:63)
  	at com.airbnb.epoxy.processor.Asyncable$DefaultImpls.awaitAndLog(Asyncable.kt:136)
  	at com.airbnb.epoxy.processor.Asyncable$awaitAndLog$1.invokeSuspend(Asyncable.kt)
  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
  Caused by: java.lang.IllegalStateException: Type mirror does not exist for android.view.ViewParent
  	at com.airbnb.epoxy.processor.Utils.areParamsTheSame(Utils.kt:325)
  	at com.airbnb.epoxy.processor.Utils.getMethodOnClass(Utils.kt:290)
  	at com.airbnb.epoxy.processor.Utils.getMethodOnClass(Utils.kt:303)
  	at com.airbnb.epoxy.processor.Utils.implementsMethod(Utils.kt:266)
  	at com.airbnb.epoxy.processor.GeneratedModelWriter.addCreateHolderMethodIfNeeded(GeneratedModelWriter.kt:1103)
  	at com.airbnb.epoxy.processor.GeneratedModelWriter.generateDefaultMethodImplementations(GeneratedModelWriter.kt:1069)
  	at com.airbnb.epoxy.processor.GeneratedModelWriter.generateClassForModel(GeneratedModelWriter.kt:148)
  	at com.airbnb.epoxy.processor.GeneratedModelWriter.generateClassForModel$default(GeneratedModelWriter.kt:121)
  	at com.airbnb.epoxy.processor.EpoxyProcessor.writeModel(EpoxyProcessor.kt:104)
  	at com.airbnb.epoxy.processor.EpoxyProcessor.access$writeModel(EpoxyProcessor.kt:25)
  	at com.airbnb.epoxy.processor.EpoxyProcessor$processRound$6.invokeSuspend(EpoxyProcessor.kt:87)
  	at com.airbnb.epoxy.processor.EpoxyProcessor$processRound$6.invoke(EpoxyProcessor.kt)
  	at com.airbnb.epoxy.processor.Asyncable$map$2$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(Asyncable.kt:30)
  	... 6 moreerror: EpoxyProcessorException: Write model failed
  com.airbnb.epoxy.processor.EpoxyProcessorException: Write model failed
  	at com.airbnb.epoxy.processor.Logger.logError(Logger.kt:63)
  	at com.airbnb.epoxy.processor.Asyncable$DefaultImpls.awaitAndLog(Asyncable.kt:136)
  	at com.airbnb.epoxy.processor.Asyncable$awaitAndLog$1.invokeSuspend(Asyncable.kt)
  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
  Caused by: java.lang.IllegalStateException: Type mirror does not exist for android.view.ViewParent
  	at com.airbnb.epoxy.processor.Utils.areParamsTheSame(Utils.kt:325)
  	at com.airbnb.epoxy.processor.Utils.getMethodOnClass(Utils.kt:290)
  	at com.airbnb.epoxy.processor.Utils.getMethodOnClass(Utils.kt:303)
  	at com.airbnb.epoxy.processor.Utils.implementsMethod(Utils.kt:266)
  	at com.airbnb.epoxy.processor.GeneratedModelWriter.addCreateHolderMethodIfNeeded(GeneratedModelWriter.kt:1103)
  	at com.airbnb.epoxy.processor.GeneratedModelWriter.generateDefaultMethodImplementations(GeneratedModelWriter.kt:1069)
  	at com.airbnb.epoxy.processor.GeneratedModelWriter.generateClassForModel(GeneratedModelWriter.kt:148)
  	at com.airbnb.epoxy.processor.GeneratedModelWriter.generateClassForModel$default(GeneratedModelWriter.kt:121)
  	at com.airbnb.epoxy.processor.EpoxyProcessor.writeModel(EpoxyProcessor.kt:104)
  	at com.airbnb.epoxy.processor.EpoxyProcessor.access$writeModel(EpoxyProcessor.kt:25)
  	at com.airbnb.epoxy.processor.EpoxyProcessor$processRound$6.invokeSuspend(EpoxyProcessor.kt:87)
  	at com.airbnb.epoxy.processor.EpoxyProcessor$processRound$6.invoke(EpoxyProcessor.kt)
  	at com.airbnb.epoxy.processor.Asyncable$map$2$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(Asyncable.kt:30)
  	... 6 morewarning: The following options were not recognized by any processor: '[kapt.kotlin.generated, room.incremental]'
```

**Comment by martymiller** [comment]
I'm having this issue as well.  It looks that to have started when I switched to Android Studio 4.2 Beta 5.

**Comment by kai91** [comment]
I'm still on Android Studio 4.1.2 and am seeing this issue as well. So it's probably not Android Studio related

**Comment by martymiller** [comment]
> I'm still on Android Studio 4.1.2 and am seeing this issue as well. So it's probably not Android Studio related

I was able to resolve my issue.  It turns out that it wasn't related to Epoxy.  Things were breaking before Epoxy was building (Room, Dagger, etc) but it looked like Epoxy was the issue when it wasn't.

**Comment by apramana** [comment]
Turning off `enableParallelEpoxyProcessing` seems to have fixed the issue for us.

**Comment by PedroMoniz** [comment]
I have the same issue, had to turn off enableParallelEpoxyProcessing. Not really a good fix.

**Comment by elihart** [comment]
enableParallelEpoxyProcessing was experimental and is removed in 5.0.0
