### ISSUE TITLE
CreateViewHolder parent is null

### ISSUE THREAD

**Issue by liuqingdada** [airbnb/epoxy#1163]
![image](https://user-images.githubusercontent.com/15871280/114006386-fa7bda00-9892-11eb-9caf-1648e20a52f2.png)

so， in [ViewBindingEpoxyModelWithHolder] createNewHolder fun :

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter parent
        at com.android.lib.uicommon.epoxy.ViewBindingEpoxyModelWithHolder.createNewHolder(Unknown Source:2)
        at com.android.lib.uicommon.epoxy.ViewBindingEpoxyModelWithHolder.createNewHolder(ViewBindingEpoxyModelWithHolder.kt:12)
        at com.airbnb.epoxy.EpoxyViewHolder.bind(EpoxyViewHolder.java:51)
        at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:118)
        at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:20)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
2021-04-08 17:52:19.013 7623-7623/com.xiaomi.captureserver E/MQSEventManagerDelegate: failed to get MQSService.

**Comment by elihart** [comment]
Can you share the version of recyclerview you are using?

**Comment by elihart** [comment]
The only way I can see a path for this to happen is if multiple model types are sharing the same view type id. In particular a `EpoxyModelWithHolder` type model looks like it would need to have the same view type as a non `EpoxyModelWithHolder` model - can you verify that you don't have any models sharing the same view type incorrectly?

**Comment by liuqingdada** [comment]
> Can you share the version of epoxy and recyclerview you are using?

'epoxy'            : "4.4.4"
'recyclerView'     : "1.1.0"

**Comment by liuqingdada** [comment]
> The only way I can see a path for this to happen is if multiple model types are sharing the same view type id. In particular a `EpoxyModelWithHolder` type model looks like it would need to have the same view type as a non `EpoxyModelWithHolder` model - can you verify that you don't have any models sharing the same view type incorrectly?

**Comment by liuqingdada** [comment]
> > The only way I can see a path for this to happen is if multiple model types are sharing the same view type id. In particular a `EpoxyModelWithHolder` type model looks like it would need to have the same view type as a non `EpoxyModelWithHolder` model - can you verify that you don't have any models sharing the same view type incorrectly?

`override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        // Attach the visibility tracker to the RecyclerView. This will enable visibility events.
        val epoxyVisibilityTracker = EpoxyVisibilityTracker()
        epoxyVisibilityTracker.partialImpressionThresholdPercentage = 75
        epoxyVisibilityTracker.attach(binding.recyclerView)
        binding.recyclerView.withModels {
            ItemViewHeader("Header Model", "This is a Data Class Item using ViewBinding")
                .id("data class view binding 1")
                .addTo(this)
            ItemViewDataClass("Data Class Item", "this is a Data Class Item")
                .id("data class 1")
                .addTo(this)
            itemViewCarouselBuilder {
                id("ItemViewCarousel 1")
                for (i in 0 until 10) {
                    itemViewCarouselCustom {
                        id("ItemViewCarouselCustom $i")
                        title("ItemViewCarouselCustom")
                        info("ItemViewCarouselCustom Info")
                    }
                }
            }
            itemViewEpoxyHolder {
                id("crash holder")
                title("test ItemViewEpoxyHolder")
                info("test info")
            }
            group {
                id("group DSL 1")
                layout(R.layout.epoxy_group_horiz_linear)
                itemViewColored {
                    id("ItemViewColored 1")
                    color(
                        ContextCompat.getColor(
                            applicationContext(),
                            R.color.miuix_appcompat_button_bg_color_warn_normal_dark
                        )
                    )
                }
                itemViewColored {
                    id("ItemViewColored 2")
                    color(
                        ContextCompat.getColor(
                            applicationContext(),
                            R.color.miuix_appcompat_button_bg_color_warn_normal_light
                        )
                    )
                }
                itemViewColored {
                    id("ItemViewColored 3")
                    color(
                        ContextCompat.getColor(
                            applicationContext(),
                            R.color.miuix_appcompat_button_bg_color_warn_pressed_dark
                        )
                    )
                }
                itemViewCarouselBuilder {
                    id("nested carousel 1")
                    for (i in 0 until 10) {
                        itemViewCarouselCustom {
                            id("nested carousel $i")
                            title("ItemViewCarouselCustom")
                            info("ItemViewCarouselCustom Info")
                        }
                    }
                }
            }
            itemViewGroup {
                id("ItemViewGroup DSL 1")
                layout(R.layout.epoxy_group_horiz_linear)
                itemViewColored {
                    id("ItemViewColored2 1")
                    color(
                        ContextCompat.getColor(
                            applicationContext(),
                            R.color.miuix_appcompat_button_bg_color_warn_pressed_dark
                        )
                    )
                }
                itemViewCarouselBuilder {
                    id("nested carousel 2")
                    for (i in 0 until 10) {
                        itemViewCarouselCustom {
                            id("nested carousel 2 $i")
                            title("ItemViewCarouselCustom")
                            info("ItemViewCarouselCustom Info")
                        }
                    }
                }
            }
            decotatedLinearGroup {
                id("decotatedLinearGroup DSL 1")
                itemViewColored {
                    id("ItemViewColored3 1")
                    color(
                        ContextCompat.getColor(
                            applicationContext(),
                            R.color.miuix_appcompat_button_bg_color_warn_pressed_dark
                        )
                    )
                }
                itemViewCarouselBuilder {
                    id("nested carousel 3")
                    for (i in 0 until 10) {
                        itemViewCarouselCustom {
                            id("nested carousel 3 $i")
                            title("ItemViewCarouselCustom")
                            info("ItemViewCarouselCustom Info")
                        }
                    }
                }
            }
            for (i in 0 until 10) {
                itemViewCustom {
                    id("${ItemViewCustom.TAG}$i")
                    color(
                        ContextCompat.getColor(
                            applicationContext(),
                            R.color.design_default_color_secondary_variant
                        )
                    )
                    title(ItemViewCustom.TAG)
                    info("This is a custom view using ModelVeiw")
                    titleListener { modle, parentView, clickedView, position ->
                        LogUtil.d(TAG, "$modle\n $parentView\n $clickedView\n $position")
                        start(ComposeFragment.newInstance())
                    }
                }
            }
        }
    }`


`@EpoxyModelClass(layout = R.layout.item_view_header)
abstract class ItemViewEpoxyHolder : ViewBindingEpoxyModelWithHolder<ItemViewHeaderBinding>() {

    @EpoxyAttribute
    lateinit var title: String

    @EpoxyAttribute
    lateinit var info: String

    override fun ItemViewHeaderBinding.bind() {
        title.text = this@ItemViewEpoxyHolder.title
        info.text = this@ItemViewEpoxyHolder.info
    }
}`

**Comment by liuqingdada** [comment]
> > The only way I can see a path for this to happen is if multiple model types are sharing the same view type id. In particular a `EpoxyModelWithHolder` type model looks like it would need to have the same view type as a non `EpoxyModelWithHolder` model - can you verify that you don't have any models sharing the same view type incorrectly?

Just an demo, no other modules to share

**Comment by elihart** [comment]
can you format your code in a readable way?

**Comment by liuqingdada** [comment]
> can you format your code in a readable way?

Excuse me, the code is already formatted

**Comment by elihart** [comment]
I can't see the view types you are using without the implementation code of the models. can you verify that you don't have any models sharing the same view type incorrectly?
