### ISSUE TITLE
NullPointerException when using EpoxyTouchHelper.initDragging

### ISSUE THREAD

**Issue by lordcodes** [airbnb/epoxy#1187]
I had a working drag implementation that was working fine with Epoxy v4.5.0.

```kotlin
EpoxyTouchHelper.initDragging(bindingController)
            .withRecyclerView(recyclerView)
            .forVerticalList()
            .withTarget(CompactCellBinder::class.java)
            .andCallbacks(ReorderDragCallback(::onCellMoved, ::onMoveComplete))
```

After updating to Epoxy v4.6.1, I now get an NPE whenever you drag a view over another. There is code in EpoxyTouchHelperCallback that is performing a cast when the ViewHolder is null. It looks like this class was converted from Java to Kotlin in this Epoxy release.

```
java.lang.NullPointerException: null cannot be cast to non-null type com.airbnb.epoxy.EpoxyViewHolder
        at com.airbnb.epoxy.EpoxyTouchHelperCallback.chooseDropTarget(EpoxyTouchHelperCallback.kt:104)
        at com.airbnb.epoxy.EpoxyTouchHelperCallback.chooseDropTarget(EpoxyTouchHelperCallback.kt:88)
        at com.airbnb.epoxy.EpoxyTouchHelperCallback.chooseDropTarget(EpoxyTouchHelperCallback.kt:11)
        at androidx.recyclerview.widget.ItemTouchHelper.moveIfNecessary(ItemTouchHelper.java:877)
        at androidx.recyclerview.widget.ItemTouchHelper$2.onTouchEvent(ItemTouchHelper.java:389)
        at androidx.recyclerview.widget.RecyclerView.dispatchToOnItemTouchListeners(RecyclerView.java:3259)
        at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3421)
```

**Comment by elihart** [comment]
Thanks for reporting, definitely seems like a mistake in the migration to kotlin and should be made to support a nullable type

**Comment by elihart** [comment]
Feel free to put up a fix if you are able to do it soon, otherwise we will get to it when we can 👍

**Comment by lordcodes** [comment]
I had a quick look, due to inheritance I think it required more changes
than just changing the function with the crash, so didn’t seem simple
without fully understanding it all. Would need some time to fully explore.

For now, I’m happy with my workaround of just rolling back to previous
minor version of Epoxy.
