### ISSUE TITLE
ViewBindingKotlinModel Proguary problem with latest gradle

### ISSUE THREAD

**Issue by AbdelrahmanHesham14** [airbnb/epoxy#1365]
```
Fatal Exception: java.lang.NullPointerException: null cannot be cast to non-null type java.lang.Class<*>
       at com.qawafel.core.epoxy.ViewBindingKotlinModelKt.getSuperclassParameterizedType(ViewBindingKotlinModel.kt:73)
       at com.qawafel.core.epoxy.ViewBindingKotlinModelKt.getSuperclassParameterizedType(ViewBindingKotlinModel.kt:73)
       at com.qawafel.core.epoxy.ViewBindingKotlinModelKt.getSuperclassParameterizedType(ViewBindingKotlinModel.kt:73)
       at com.qawafel.core.epoxy.ViewBindingKotlinModelKt.getSuperclassParameterizedType(ViewBindingKotlinModel.kt:73)
       at com.qawafel.core.epoxy.ViewBindingKotlinModelKt.getBindMethodFrom(ViewBindingKotlinModel.kt:64)
       at com.qawafel.core.epoxy.ViewBindingKotlinModelKt.access$getBindMethodFrom(ViewBindingKotlinModel.kt:1)
       at com.qawafel.core.epoxy.ViewBindingKotlinModel$bindingMethod$2.invoke(ViewBindingKotlinModel.kt:29)
       at com.qawafel.core.epoxy.ViewBindingKotlinModel$bindingMethod$2.invoke(ViewBindingKotlinModel.java:29)
```

**Comment by BlackFish768** [comment]
Same here. +1

I added this in Proguard as mentioned in the ViewBindingKotlinModel class

-keepclassmembers class * extends androidx.viewbinding.ViewBinding {
     public static *** bind(android.view.View);
}

but still getting the same NullPointerException.

**Comment by AbdelrahmanHesham14** [comment]
@BlackFish768 Yes it's very weired
@elihart Please advise here

**Comment by john-tadebois** [comment]
I get the same error with the following specs:

AGP 8.0.0
com.airbnb.android:epoxy - v5.1.3
Same stacktrace as posted in the details of this issue.

**Comment by AbdelrahmanHesham14** [comment]
No response from the team till now !
Anyone found a solution ?!

**Comment by cemore2048** [comment]
Don't know how helpful this is a year later. When you update to AGP 8 it forces `android.enableR8.fullMode` to true. it's a more aggressive code minification. you have to explicitly set it to false in your `gradle.properties` file

android.enableR8.fullMode=false

That should avoid the need to figure out what rule to add

**Comment by Nephys222** [comment]
@cemore2048 solutions fixed for me. But does it acceptable to close the bug.

**Comment by dmytroreutov** [comment]
Having exact same issue with AGP 8.8.2. 
`android.enableR8.fullMode = false` did the trick, but it cannot be considered as permanent fix.

**Comment by BlackFish768** [comment]
Since it has not been fixed after all these years. Heres an alternative approach to use viewbinding if anyone's interested:

`@EpoxyModelClass
open class HeaderEpoxyModel : EpoxyModelWithHolder<HeaderEpoxyModel.MyViewHolder>() {

    class MyViewHolder : EpoxyHolder() {
        lateinit var binding: ItemHeaderBinding

        override fun bindView(itemView: View) {
            binding = ItemHeaderBinding.bind(itemView)
        }
    }

    @EpoxyAttribute
    lateinit var headerItem: HeaderItem

    @EpoxyAttribute
    var clickListener: ((HeaderItem) -> Unit)? = null

    override fun bind(holder: MyViewHolder) {
        super.bind(holder)

        with(holder.binding) {
            tvTitle.text = headerItem.title

            buttonSeeAll.setOnClickListener {
                clickListener?.invoke(headerItem)
            }
        }
    }

    override fun unbind(holder: MyViewHolder) {
        super.unbind(holder)

        with(holder.binding) {
            buttonSeeAll.setOnClickListener(null)
        }
    }

    override fun getDefaultLayout(): Int = R.layout.item_header

    override fun createNewHolder(parent: ViewParent): MyViewHolder = MyViewHolder()
}`

P.S: Some boilerplate can be abstracted to a BaseEpoxyModel class.

**Comment by dmytroreutov** [comment]
Seems like `android.enableR8.fullMode = false` should not be used in future.
https://android-developers.googleblog.com/2026/08/app-quality-memory-optimization-secure-onboarding.html
