### ISSUE TITLE
Unexpected type name for KSType: java.util.ArrayList<E>

### ISSUE THREAD

**Issue by ritesh-singh** [airbnb/epoxy#1373]
e: [ksp] java.lang.IllegalStateException: Unexpected type name for KSType: java.util.ArrayList<E>
        at androidx.room.compiler.processing.ksp.KSTypeJavaPoetExtKt.asJTypeName(KSTypeJavaPoetExt.kt:204)
        at androidx.room.compiler.processing.ksp.KSTypeJavaPoetExtKt.asJTypeName(KSTypeJavaPoetExt.kt:67)
        at androidx.room.compiler.processing.ksp.KSTypeJavaPoetExtKt.asJTypeName$resolveTypeName(KSTypeJavaPoetExt.kt:149)
        at androidx.room.compiler.processing.ksp.KSTypeJavaPoetExtKt.asJTypeName(KSTypeJavaPoetExt.kt:160)
        at androidx.room.compiler.processing.ksp.KSTypeJavaPoetExtKt.asJTypeName(KSTypeJavaPoetExt.kt:183)
        at androidx.room.compiler.processing.ksp.KSTypeJavaPoetExtKt.asJTypeName(KSTypeJavaPoetExt.kt:170)
        at androidx.room.compiler.processing.ksp.DefaultKspType.resolveJTypeName(DefaultKspType.kt:34)
        at androidx.room.compiler.processing.ksp.KspType$xTypeName$2.invoke(KspType.kt:67)
        at androidx.room.compiler.processing.ksp.KspType$xTypeName$2.invoke(KspType.kt:65)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at androidx.room.compiler.processing.ksp.KspType.getXTypeName(KspType.kt:65)
        at androidx.room.compiler.processing.ksp.KspType.access$getXTypeName(KspType.kt:49)
        at androidx.room.compiler.processing.ksp.KspType$typeName$2.invoke(KspType.kt:62)
        at androidx.room.compiler.processing.ksp.KspType$typeName$2.invoke(KspType.kt:61)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at androidx.room.compiler.processing.ksp.KspType.getTypeName(KspType.kt:61)
        at com.airbnb.epoxy.processor.BaseModelAttributeInfo.buildAnnotationLists(BaseModelAttributeInfo.kt:219)
        at com.airbnb.epoxy.processor.BaseModelAttributeInfo.<init>(BaseModelAttributeInfo.kt:63)
        at com.airbnb.epoxy.processor.EpoxyProcessor$Companion.buildAttributeInfo(EpoxyProcessor.kt:272)
        at com.airbnb.epoxy.processor.EpoxyProcessor.processRound(EpoxyProcessor.kt:74)
        at com.airbnb.epoxy.processor.BaseProcessor.processRoundInternal(BaseProcessor.kt:223)
        at com.airbnb.epoxy.processor.BaseProcessor.process(BaseProcessor.kt:149)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:306)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:304)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:410)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:304)

**Comment by ritesh-singh** [comment]
Looks very similar to https://github.com/google/ksp/issues/881 - looks like it was fixed in recent version of ksp.

**Comment by DastanIqbal** [comment]
Any update on this facing similar issue after migrating epoxy to ksp  
[ksp] java.lang.IllegalStateException: Unexpected type name for KSType: java.util.HashMap<K, V>
	at androidx.room.compiler.processing.ksp.KSTypeJavaPoetExtKt.asJTypeName(KSTypeJavaPoetExt.kt:204)


Epoxy v5.1.4
KSP: 1.9.20-1.0.14
Kotlin: 1.9.20
