### ISSUE TITLE
ProGuard issue with @AutoModel in my BaseController

### ISSUE THREAD

**Issue by jbmlaird** [airbnb/epoxy#197]
Are you guys using any ProGuard rules with your autogenerated classes?

I tried `@AutoModel`ing a `HeaderModel` in a `BaseController` class but whenever I have a `Controller` that uses this base class, it will throw a NPE. Perhaps it's my implementation

```
public abstract class BaseController extends EpoxyController
{
    public String title = "";
    public String subtitle = "";
    public String imageUrl = "";

    // Can't use this as ProGuard causes issues with AutoModels
    // public @AutoModel HeaderModel_ header;

    public void setTitle(String title)
    {
        this.title = title;
    }
}
```

My stacktrace:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{bj.rxjavaexperimentation/bj.rxjavaexperimentation.artist.ArtistActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'bj.rxjavaexperimentation.epoxy.common.c bj.rxjavaexperimentation.epoxy.common.c.u(android.content.Context)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
        at android.app.ActivityThread.-wrap14(ActivityThread.java:-1)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'bj.rxjavaexperimentation.epoxy.common.c bj.rxjavaexperimentation.epoxy.common.c.u(android.content.Context)' on a null object reference

        at bj.rxjavaexperimentation.artist.ArtistController.void buildModels()(ArtistController.java:39) <---- here

        at com.airbnb.epoxy.EpoxyController.void dispatchModelBuild()(EpoxyController.java:126)
        at com.airbnb.epoxy.EpoxyController.void requestModelBuild()(EpoxyController.java:73)
        at bj.rxjavaexperimentation.artist.ArtistPresenter.void setupRecyclerView(android.content.Context,android.support.v7.widget.RecyclerView,java.lang.String)(ArtistPresenter.java:72)
        at bj.rxjavaexperimentation.artist.ArtistActivity.void onCreate(android.os.Bundle)(ArtistActivity.java:47)
        at android.app.Activity.performCreate(Activity.java:6912)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
        at android.app.ActivityThread.-wrap14(ActivityThread.java:-1)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

```

Relevant line in class

```
header
        .context(context)
        .title(title)
        .subtitle(subtitle)
        .imageUrl(imageUrl)
        .addTo(this);
```

Again, this is fine without using ProGuard. Perhaps it's best practice to not abstract models in this fashion? I am no longer including the `HeaderModel_` in that base class and creating a new one in each `Controller`.

**Comment by elihart** [comment]
Are you sure it is ProGuard causing the issue? I think AutoModel annotation on super classes will just never work because I didn't build support for it into the annotation processor. I considered that case but didn't build it since I thought it would be uncommon, it should be fairly easy to support if people want it though.

You do bring up a good point about proguard though. We haven't had issues with it, but we don't use it aggressively. I imagine that we would need rules very similar to butterknife's (https://github.com/JakeWharton/butterknife/blob/master/butterknife/proguard-rules.txt) to keep the generated controller helpers working correctly.

I'm not too familiar with proguard rules, but I can work on that if somebody needs it, or it'd be great to have some help :)

**Comment by elihart** [comment]
Created an issue for the inheritance case https://github.com/airbnb/epoxy/issues/198

**Comment by jbmlaird** [comment]
I'll see if I can get some ProGuard rules working.

**Comment by tomoima525** [comment]
Hi guys, I just want to share that I had the same issue with `@AutoModel` and Proguard. Trying to add proguard setting
