### ISSUE TITLE
EpoxyController.setData() vs. EpoxyController.requestModelBuild()

### ISSUE THREAD

**Issue by fredo-** [airbnb/epoxy#257]
Hey guys love the library, great work!

I'm having some problems updating views once they're set up though.

I'm trying to set up a list and change its contents based on state on the UI. I have my callbacks and models working properly, but when I call `setData()` and the ModelGroups are built and the Models are created, the list doesn't update with the new data. 

We tried using the pattern seen in the sample app with the colors in the carousels, and the pattern used in the Epoxy Controller section of the Wiki (this second one does not work and throws an exception that we should be using `setData()` instead)

Here's the controller.buildModels(): 

```
   @Override
    protected void buildModels(SearchViewModel.State state) {
        String cityName = state.getCity().getName();
        header.title("Shows this week in")
                .caption(cityName)
                .callback(callbacks);
        add(header);


        ArrayList<CarouselEventModel_> carouselList = getEventModels(state.getCarouselEventList());

        if (state.getCarouselEventList().size() > 0) {
            Timber.e("carousel size = %s", state.getCarouselEventList().size());
            add(new CarouselModelGroup(new CarouselData("Most Popular in New York", 0, carouselList))
            .id(1));
        }
        
        if (state.getVerticalEventList().size() > 0) {
            add(new EverythingFilterModelGroup(state.getGenreList(), 20, state.isGenreDrawerVisible(), callbacks)
            .id(2));
            ArrayList<FilterPillModel_> filterButtons = getFilterButtonModels(state.getGenreList(), callbacks);
            if (state.isGenreDrawerVisible()) {
                add(new FilterOptionsModel_()
                        .reset()
                        .id(100)
                        .models(filterButtons));
            }
            ArrayList<ListEventModel_> listList = getListModels(state.getVerticalEventList());
            add(listModel.models(listList));
            add(footerModel.title("That's all!")
                    .notifyText("Notify me when there are new shows to check out:")
                    .feedbackText("Would you mind giving us some feedback?")
                    .yesBtnTxt("Ok, Sure!")
                    .noBtnTxt("Not Really"));
        }
    }
```
This is how I set up the Models for the List that we're trying to update:
```
    @NonNull
    private ArrayList<ListEventModel_> getListModels(List<Event> events) {
        ArrayList<ListEventModel_> list = new ArrayList<>();
        for (Event event : events) {
            String dateStr = event.getDates().getStart().getLocalTime();
            String artist = "";
            if (event.get_embedded().getAttractions() != null) {
                artist = event.get_embedded().getAttractions().get(0).getName();
            }
            ListEventModel_ model = new ListEventModel_()
                    .id(event.getId())
                    .imageUrl(getLargeImage(event.getImages()).getUrl())
                    .artistString((artist != null) ? artist : "")
                    .dateTimeString((dateStr != null) ? getTimeString(event) : "")
                    .venueString(event.get_embedded().getVenues().get(0).getName())
                    .priceString("$" + ((event.getPriceRanges() != null)
                            ? event.getPriceRanges().get(0).getMin() : "0"))
                    .clickListener(new OnModelClickListener() {
                        @Override
                        public void onClick(EpoxyModel model, Object parentView, View clickedView, int position) {
                            callbacks.onListEventClicked(position);
                        }
                    });

            list.add(model);
        }
        return list;
    }
```

The first time we call `setModels()` everything is drawn correctly, but when we create a different list (with fewer `ListEventModel`s) the views do not change. From the sample app and the documentation, the views in `listModel` should update when we pass to it a different list of `ListEventModel`s but it's not updating. 

Here's the ListModel declaration just in case: 
```
@EpoxyModelClass
public abstract class ListModel extends EpoxyModelWithView<RecyclerView> {
    @EpoxyAttribute
    List<? extends EpoxyModel<?>> models;

    @Override
    public boolean shouldSaveViewState() {
        return true;
    }

    @Override
    protected RecyclerView buildView(ViewGroup parent) {
        RecyclerView recView = new RecyclerView(parent.getContext(), null);
        RecyclerView.LayoutManager layoutManager =
                new LinearLayoutManager(parent.getContext(), LinearLayoutManager.VERTICAL, false);
        recView.setLayoutManager(layoutManager);
        SimpleEpoxyController controller = new SimpleEpoxyController();
        controller.setSpanCount(1);
        recView.setAdapter(controller.getAdapter());
        controller.setModels(models);
        return recView;
    }
}
```

**Comment by elihart** [comment]
you're setting the models in `buildView`, not `bind`.

buildView should just create the view, `bind` is where you update data on the view

**Comment by elihart** [comment]
Look at `CarouselModel` more carefully in the sample.

I've also been meaning to write up a Carousel sample in the wiki

**Comment by fredo-** [comment]
Gotcha, I think I know what you mean. I am using RecyclerView as the view so my code in `bind` looks very similar to `buildView`

I updated my ListModel class to look like this, but I'm now getting an `IndexOutOfBoundsException` because my state is 25 (from the first time I set it up, there are 25 views in my list), and I'm trying to update to 9 (because now I only want 9 views in the list): 

```
@EpoxyModelClass
public abstract class ListModel extends EpoxyModelWithView<RecyclerView> {
    @EpoxyAttribute
    List<? extends EpoxyModel<?>> models;
    //If we want the bind() and bindView() methods to look like sample app, we need
    //to create a class List extends RecyclerView, because that object is what will be
    //saved and stored and it can save instance variables like the controller, layoutManager etc
    //The created List object is what would be saved and passed to bind()

    @Override
    public boolean shouldSaveViewState() {
        return false;
    }

    @Override
    protected RecyclerView buildView(ViewGroup parent) {
        RecyclerView recView = new RecyclerView(parent.getContext(), null);
        RecyclerView.LayoutManager layoutManager =
                new LinearLayoutManager(parent.getContext(), LinearLayoutManager.VERTICAL, false);
        recView.setLayoutManager(layoutManager);
        SimpleEpoxyController listController = new SimpleEpoxyController();
        listController.setSpanCount(1);
        recView.setAdapter(listController.getAdapter());
        listController.setModels(models);
        return recView;
    }

    @Override
    public void bind(RecyclerView recView) {
        RecyclerView.LayoutManager layoutManager =
                new LinearLayoutManager(recView.getContext(), LinearLayoutManager.VERTICAL, false);
        recView.setLayoutManager(layoutManager);
        SimpleEpoxyController listController = new SimpleEpoxyController();
        listController.setSpanCount(1);
        recView.setAdapter(listController.getAdapter());
        listController.setModels(models);
    }
}
```

and the Exception: 
```
Process: com.tmsdurham.shortlist, PID: 10073
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:9).state:25
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)                                                        
```

**Comment by elihart** [comment]
nice :) I'd highly recommend also clearing the models in unbind btw to clean up resources. the sample app shows that
