### ISSUE TITLE
Configuration in Kotlin

### ISSUE THREAD

**Issue by mradzinski** [airbnb/epoxy#288]
Hi, we are currently developing a project using Kotlin and would love to be able to configure Epoxy from Gradle. As per de docs we should include in our build.gradle:

```
project.android.buildTypes.all { buildType ->
    buildType.javaCompileOptions.annotationProcessorOptions.arguments =
            [
                    // Validation is disabled in production to remove the runtime overhead
                    validateEpoxyModelUsage     : String.valueOf(buildType.name == 'debug'),
                    requireHashCodeInEpoxyModels: "true",
                    requireAbstractEpoxyModels  : "true",
                    implicitlyAddAutoModels     : "true"
            ]
}
```

However, it seems that after including this the project does not compile anymore. Gradle output states:

```
java.lang.IllegalStateException: failed to analyze: org.jetbrains.kotlin.kapt3.diagnostic.KaptError: Error while annotation processing
	at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:57)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules(KotlinToJVMBytecodeCompiler.kt:138)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:170)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:58)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:93)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:46)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:386)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$compile$1$2.invoke(CompileServiceImpl.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:832)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl$doCompile$$inlined$ifAlive$lambda$2.invoke(CompileServiceImpl.kt:98)
	at org.jetbrains.kotlin.daemon.common.DummyProfiler.withMeasure(PerfUtils.kt:137)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.checkedCompile(CompileServiceImpl.kt:859)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.doCompile(CompileServiceImpl.kt:831)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:385)
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Should we need to modify anything in order to configure Expoy from Gradle?

**Comment by mradzinski** [comment]
Ok, it has to do with `requireAbstractEpoxyModels  : "true"`. Removing this line fixes up the issue. It seems abstract epoxy models aren't working in Kotlin.

**Comment by elihart** [comment]
Thanks for reporting. Did you have any classes annotated with `@EpoxyModelClass` that weren't abstract that would have triggered this? Or did it just fail outright?

Seems bad regardless - I'll try to repro in a sample project.

Is everything working now that you've removed that?

**Comment by mradzinski** [comment]
All annotated classes were abstract (actually triple checked this), it was just failing through, and I guess it has something to do with abstract classes in Kotlin and how they work. After removing the configuration param and reverting to use regular Kotlin classes it worked perfectly fine.

I'll see of creating a sample project too, it's quite intriguing to understand the differences and why it broke in Kotlin (I've actually been using Epoxy on a Java project too with that configuration enabled and had no problems at all).

**Comment by elihart** [comment]
Thanks for the details! It is strange that kotlin would be having this issue - I'm curious what is going on. Will try to look into it soonish, but hopefully for now you and others can leave this option out.

**Comment by elihart** [comment]
I'll also update the wiki

**Comment by elihart** [comment]
@mradzinski Did you happen to try cleaning the project between when you made the gradle change and building?

I got this same issue from something different and I needed to clean before it worked properly.

**Comment by elihart** [comment]
I tried to reproduce this but it worked fine with a single kotlin class https://github.com/airbnb/epoxy/compare/eli-abstract_models_failure_kotlin?expand=1

I'm guessing there is some more complex interaction going on that it hard to reproduce.

If you can reproduce it in a sample project, or verify that cleaning doesn't fix it, that would be helpful.

**Comment by mradzinski** [comment]
Hey @elihart, sorry, been quite busy. Yes, there's defo a more complex interaction. I tried reproducing the same on a clean project and couldn't so I must asume there's something else effing up KAPT. We can close this now because its working. If I encounter once more with this error I'll try digging deeper into which dependency can be the problematic one when mixed with Epoxy.
