### ISSUE TITLE
NoSuchElementException while computing `toString()`

### ISSUE THREAD

**Issue by shaishavgandhi05** [airbnb/epoxy#455]
This one is a little hard to explain but here goes:
I have a model which has a lambda declared in this way:
```kotlin
@EpoxyModelClass abstract class MyModel: EpoxyModelWithHolder<MyHolder>() {
  @EpoxyAttribute lateinit var clickListener: (param1: Param1, view: ImageView?) -> Unit
}

```

From Crashlytics, I'm getting a Kotlin collections error. The stacktrace is something like this:
`Caused by java.util.NoSuchElementException: Collection is empty.
       at kotlin.collections.s.first(_Collections.kt:166)
       at kotlin.reflect.jvm.internal.impl.builtins.b$a.<clinit>(BuiltInsLoader.kt:38)
       at kotlin.reflect.jvm.internal.impl.builtins.b.<clinit>(Unknown Source)
       at kotlin.reflect.jvm.internal.impl.builtins.i.b(KotlinBuiltIns.java:148)
       at kotlin.reflect.jvm.internal.impl.a.b.<init>(JvmBuiltIns.kt:56)
       at kotlin.reflect.jvm.internal.impl.a.b.<init>(JvmBuiltIns.kt:31)
       at kotlin.reflect.jvm.internal.z.a(moduleByClassLoader.kt:1054)
       at kotlin.reflect.jvm.internal.ag.a(util.kt:162)
       at kotlin.reflect.jvm.internal.ab.renderLambdaToString(ReflectionFactoryImpl.java:15046)
       at kotlin.jvm.internal.Reflection.renderLambdaToString(Reflection.java:80)
       at kotlin.jvm.internal.Lambda.toString(Lambda.kt:22)
       at java.lang.String.valueOf(String.java:2827)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at com.myapp.mypackage.mymodels.models.MyModel_.toString(MyModel_.java:231)
       at java.lang.String.valueOf(String.java:2827)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at com.airbnb.epoxy.DiffHelper.createStateForPosition(DiffHelper.java:234)
       at com.airbnb.epoxy.DiffHelper.prepareStateForDiff(DiffHelper.java:221)
       at com.airbnb.epoxy.DiffHelper.buildDiff(DiffHelper.java:173)
       at com.airbnb.epoxy.DiffHelper.notifyModelChanges(DiffHelper.java:133)
       at com.airbnb.epoxy.EpoxyControllerAdapter.setModels(EpoxyControllerAdapter.java:47)
       at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:188)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

I haven't been able to reproduce this issue on my own but I'm getting significant number of crashes in the wild.

**Comment by elihart** [comment]
Thanks for sharing. Looking at the stacktrace the epoxy method is
```
private ModelState createStateForPosition(int position) {
    EpoxyModel<?> model = adapter.getCurrentModels().get(position);
    model.addedToAdapter = true;
    ModelState state = ModelState.build(model, position, immutableModels);

    ModelState previousValue = currentStateMap.put(state.id, state);
    if (previousValue != null) {
      int previousPosition = previousValue.position;
      EpoxyModel<?> previousModel = adapter.getCurrentModels().get(previousPosition);
      throw new IllegalStateException("Two models have the same ID. ID's must be unique!"
          + " Model at position " + position + ": " + model
          + " Model at position " + previousPosition + ": " + previousModel);
    }

    return state;
  }
```

To string is only being called on your model because it was going to throw an exception anyway. The root problem is you have duplicate ids - fix that and the crash should go away.

It would be nice if `toString` wasn't crashing though. It seems like calling toString on the lambda is leading to a kotlin crash, which may be a kotlin bug. Not sure what I can do about that

**Comment by shaishavgandhi05** [comment]
Just to further report on this, I actually did try fixing the IDs issue by using `setFilterDuplicates(true). However, the Kotlin lambda issue still causes the crash. In the `filterDuplicatesIfNeeded` method, Epoxy swallows the Exception with this line
```java
onExceptionSwallowed(
            new IllegalEpoxyUsage("Two models have the same ID. ID's must be unique!"
                + "\nOriginal has position " + indexOfOriginal + ":\n" + originalModel
                + "\nDuplicate has position " + indexOfDuplicate + ":\n" + model)
        );
```

This causes the crash again since the `toString()` on the model is called again. 
For now, I will remove the lambda to resolve the crash. 

However, I would like to propose omitting the lambda from the `toString()` implementation till this bug is resolved. It's not ideal, but this would save people from trouble. We can add a TODO which mentions that the lambda is omitted from the `toString()` implementation until it's further resolved by Kotlin.

**Comment by elihart** [comment]
Fixed with https://github.com/airbnb/epoxy/pull/482

**Comment by shaishavgandhi05** [comment]
Thanks Eli!
