### ISSUE TITLE
NullPointerException in RecyclerView

### ISSUE THREAD

**Issue by harshitwynk** [airbnb/epoxy#585]
Hi

I am getting following crash in Recyclerview while using Epoxy

> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.recyclerview.widget.RecyclerView$ViewHolder.shouldIgnore()' on a null object reference
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3951)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3652)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:19590)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at androidx.appcompat.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1645)
        at androidx.appcompat.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1499)
        at androidx.appcompat.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1407)
        at android.view.View.layout(View.java:19590)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9322)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1615)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:19590)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:19590)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19590)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19590)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19590)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19590)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19590)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
        at android.view.View.layout(View.java:19590)
        at android.view.ViewGroup.layout(ViewGroup.java:6053)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
2018-10-20 19:24:30.408 20730-20730/com.wynk.basic E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Epoxy version used : 2.19.0
Language : kotlin
Android version : 8.0.0

**Comment by yen223** [comment]
I encountered this a while back.

In my case the root cause was duplicate IDs among list items. Fixed it by ensuring IDs were truly unique.

Another workaround was to disable item animations

**Comment by elihart** [comment]
yes this issue is most likely caused by not having proper ids (either ids that change, or are duplicates)

make sure your ids are stable, and I would recommend enabling the debug setting to filter and crash on duplicate ids so you can catch this in debug early (or enable filtering ids in prod but log the warning somewhere)

**Comment by pcrish** [comment]
I found this issue when using fragment, the issue was that I was trying to replace fragment, I fixed it by putting FrameLayout and replacing fragment in it.

**Comment by kalyakiplangat** [comment]
if you have include tag that includes the RecyclerView Layout, make sure that the include tag has an id and use findViewById

**Comment by E-Learning567** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.bloodbankmanagementsystem/com.example.bloodbankmanagementsystem.Activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View androidx.recyclerview.widget.RecyclerView.findViewById(int)' on a null object reference

**Comment by E-Learning567** [comment]
How to fix it ?

**Comment by E-Learning567** [comment]
Kindly help me

**Comment by Aram-dev** [comment]
https://stackoverflow.com/a/47436165

**Comment by Nobler** [comment]
> yes this issue is most likely caused by not having proper ids (either ids that change, or are duplicates)
> 
> make sure your ids are stable, and I would recommend enabling the debug setting to filter and crash on duplicate ids so you can catch this in debug early (or enable filtering ids in prod but log the warning somewhere)

@elihart Hi, could you please explain why the duplicated id cause that NPE issue?

**Comment by tinder-cesardiez** [comment]
@elihart Hi there! 

Regarding this:

> I would recommend enabling the debug setting to filter and crash on duplicate ids

I didn't see any developer settings nor RecyclerView API allowing us to crash when finding duplicate ids. Any chance you could elaborate on this? We are currently running into an issue in production and we are certain ids are never duplicate. We are working with Google to understand why `mChildHelper.getChildAt(i)` is returning null, but anything that could help us out debugging this would definitely help!

Here's the code in crime:

![image](https://github.com/airbnb/epoxy/assets/71292539/2cd8875b-074d-44c0-b1a9-d60a30f156cb)

**Comment by cyl0102** [comment]
> [@elihart](https://github.com/elihart) Hi there!  你好呀！
> 
> Regarding this:  关于这一点：
> 
> > I would recommend enabling the debug setting to filter and crash on duplicate ids我建议启用调试设置来过滤重复的 ID 并避免崩溃
> 
> I didn't see any developer settings nor RecyclerView API allowing us to crash when finding duplicate ids. Any chance you could elaborate on this? We are currently running into an issue in production and we are certain ids are never duplicate. We are working with Google to understand why `mChildHelper.getChildAt(i)` is returning null, but anything that could help us out debugging this would definitely help!我没有看到任何开发者设置或 RecyclerView API 允许我们在发现重复 ID 时崩溃。您能详细说明一下吗？我们目前在生产环境中遇到了一个问题，我们确定 ID 绝对不会重复。我们正在与 Google 合作，以了解为什么 `mChildHelper.getChildAt(i)` 返回 null，但任何可以帮助我们调试这个问题的方法都绝对有用！
> 
> Here's the code in crime:以下是犯罪代码：
> 
> ![image](https://github.com/airbnb/epoxy/assets/71292539/2cd8875b-074d-44c0-b1a9-d60a30f156cb)

I've encountered the same problem, have you solved it
