### ISSUE TITLE
Generic epoxy model causes exception

### ISSUE THREAD

**Issue by kusraevs** [airbnb/epoxy#645]
I try to inherit generic epoxy model from EpoxyModel like below
```
@EpoxyModelClass(layout = R.layout.category_item_layout)
abstract class CategoryServiceMasterModel<T: ServiceHolder<T>> : EpoxyModel<CategoryViewI>() {
    @EpoxyAttribute
    lateinit var serviceSection: ServiceSection<T>
    @EpoxyAttribute(hash = false)
    var clickListener: CategoryClickListener<T>? = null
}
```
And my build failed with an exception

`> Task :master:transformDataBindingWithDataBindingMergeArtifactsForStagingMinApi21Debug 
e: [kapt] An exception occurred: java.lang.StackOverflowError
	at com.airbnb.epoxy.PoetExtensionsKt.toKPoet(PoetExtensions.kt)
	at com.airbnb.epoxy.PoetExtensionsKt.toKPoet(PoetExtensions.kt:133)
	at com.airbnb.epoxy.PoetExtensionsKt.toKPoet(PoetExtensions.kt:184)
	at com.airbnb.epoxy.PoetExtensionsKt.toKPoet$default(PoetExtensions.kt:171)
	at com.airbnb.epoxy.PoetExtensionsKt.toKPoet(PoetExtensions.kt:198)
	at com.airbnb.epoxy.PoetExtensionsKt.toKPoet(PoetExtensions.kt:168)
	at com.airbnb.epoxy.PoetExtensionsKt.toKPoet(PoetExtensions.kt:186)
	at com.airbnb.epoxy.PoetExtensionsKt.toKPoet$default(PoetExtensions.kt:171)
`

**Comment by elihart** [comment]
I think this is mostly a bug with kotlin handling - can you convert it to java and see if it works?
