### ISSUE TITLE
Manifest merger failed with multiple errors

### ISSUE THREAD

**Issue by hdtuan87** [airbnb/epoxy#666]
my app gradle:
`//top file gralde
apply plugin: 'kotlin-kapt'

dependencies{
    //epoxy
    implementation 'com.airbnb.android:epoxy:3.1.0'
    annotationProcessor 'com.airbnb.android:epoxy-processor:3.1.0'
}`

error:
`aused by: java.lang.RuntimeException: Manifest merger failed with multiple errors, see logs
	at com.android.builder.core.AndroidBuilder.mergeManifestsForApplication(AndroidBuilder.java:540)
	at com.android.build.gradle.tasks.MergeManifests.doFullTaskAction(MergeManifests.java:173)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
	at sun.reflect.GeneratedMethodAccessor2235.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 34 more

`

**Comment by elihart** [comment]
` Manifest merger failed with multiple errors, see logs` - can you give information from the logs?

without more information there's not much I can do

**Comment by solt9029** [comment]
I got the same error. I just added epoxy(3.1.0) into my dependencies and conducted rebuild, then the error happened.
I'm using Android Studio 3 if it helps.

**Comment by budioktaviyan** [comment]
I also got this issue

```Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:5-47:19 to override.```

**Comment by arnorhs** [comment]
I'm seeing the same thing when trying to add Epoxy to an existing project, and my log says:

```
	Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:34:5-118:19 to override.
```

it seems like androidx.xx dependencies shouldn't be included .. so does Epoxy require the androidx variant of the support libs?

**Comment by elihart** [comment]
@arnorhs @budioktaviyan Epoxy 3.0.0+ uses Androidx - if you don't use Androidx you can use an older version of Epoxy

**Comment by BunsinNANH** [comment]
my app gradle:
dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'com.android.tools.build:gradle:3.4.0'

my issue:

Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs


How I can solve it please give me some idea

**Comment by ashishpatel1512** [comment]
i am getting this error.

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

can some help me out.? thanks in advanced.

**Comment by DrMkcTheHandSome** [comment]
I NEED SOME HELP I ALSO HAVE THE SAME PROBLEM WITH YOU GUYS.  HOW CAN WE SOLVE THIS ?

**Comment by vuongquocthanh** [comment]
Convert to androidx -> solved

**Comment by ifjgm005** [comment]
when I add dependence like this "compile 'cat.ereza:customactivityoncrash:2.3.0'".
This library allows launching a custom activity when the app crashes, instead of showing the hated "Unfortunately, X has stopped" dialog.then I got the same error.
solved steps:
1: compile 'cat.ereza:customactivityoncrash:1.5.0'
2: solved
3: compile 'cat.ereza:customactivityoncrash:2.3.0
4: the error gone

I don't know why!!!
