### ISSUE TITLE
EpoxyVisibilityTracker - IllegalArgumentException

### ISSUE THREAD

**Issue by gokulkrizh** [airbnb/epoxy#700]
**Senario** -  when come back to the activity that backstacked i had this exception thrown. Checked again its not throwing exception. Don't know what the issue is
I'm injecting EpoxyVisibilityTracker from dagger...
Is it necessary to detach EpoxyVisibilityTracker when activity is paused?. and also re-attach in onResume of activity

`Fatal Exception: java.lang.IllegalArgumentException: View android.widget.LinearLayout{545b595 VFE...C.. ......ID 0,2143-1440,2293} is not a direct child of com.airbnb.epoxy.EpoxyRecyclerView{57f3ff7 VFED..... ........ 0,0-1440,2429 #7f0a018f app:id/view_recycler}
       at android.support.v7.widget.RecyclerView.getChildViewHolder(RecyclerView.java:4561)
       at com.airbnb.epoxy.EpoxyVisibilityTracker.processChild(EpoxyVisibilityTracker.java:169)
       at com.airbnb.epoxy.EpoxyVisibilityTracker.access$200(EpoxyVisibilityTracker.java:36)
       at com.airbnb.epoxy.EpoxyVisibilityTracker$Listener.onChildViewDetachedFromWindow(EpoxyVisibilityTracker.java:273)
       at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:7261)
       at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:867)
       at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
       at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:8374)
       at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:8647)
       at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleAllViews(RecyclerView.java:10080)
       at android.support.v7.widget.RecyclerView.removeAndRecycleViews(RecyclerView.java:1174)
       at android.support.v7.widget.RecyclerView.setAdapterInternal(RecyclerView.java:1197)
       at android.support.v7.widget.RecyclerView.swapAdapter(RecyclerView.java:1140)
       at com.airbnb.epoxy.EpoxyRecyclerView.swapAdapter(EpoxyRecyclerView.java:505)
       at com.airbnb.epoxy.EpoxyRecyclerView.removeAdapter(EpoxyRecyclerView.java:543)
       at com.airbnb.epoxy.EpoxyRecyclerView.access$100(EpoxyRecyclerView.java:67)
       at com.airbnb.epoxy.EpoxyRecyclerView$1.run(EpoxyRecyclerView.java:148)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by eboudrant** [comment]
@gokukish I am not familiar with Dagger, would you mind sharing some code ? The best would be to have a sample project where we could reproduce it. Btw, can you easily reproduce the crash ? Happen all the time ?

I see the `swapAdapter` is coming from a async runnable, it may cause the bug. Then a view get passed to `onChildViewDetachedFromWindow` without parent, I haven't seen that before...

Also just to confirm, there is no need to detach on activity paused.
