### ISSUE TITLE
Model Groups and Databinding DSL

### ISSUE THREAD

**Issue by nealsanche** [airbnb/epoxy#800]
Hi all!

Have been using Epoxy for a few months and really like the Databinding DSLs that are generated, however, ran into an issue the other day and wonder how to proceed correctly. Here's what I've been doing.

Made a little Kotlin class:

```
    class AccountWithTransactions(models: List<EpoxyModel<*>>) : EpoxyModelGroup(R.layout.epoxy_account_model_group, models)
```

My model group layout is simple (pretty much as documented):

```
<?xml version="1.0" encoding="utf-8"?>
<com.google.android.material.card.MaterialCardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginStart="16dp"
    android:layout_marginEnd="16dp"
    app:cardElevation="4dp"
    app:layout_constraintEnd_toEndOf="parent"
    app:layout_constraintStart_toStartOf="parent"
    app:layout_constraintTop_toTopOf="parent">

    <LinearLayout
        android:id="@+id/epoxy_model_group_child_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical" />

</com.google.android.material.card.MaterialCardView>
```

We've gone and lifted the `simpleController` extension functions from one of the Epoxy demos (or maybe it's MvRx demos). So we've gotten used to using the DSL for our DataBinding layouts. But when it comes to adding models to the `AccountWithTransactions` model group, we haven't figured out a way to use the DSL for this and have to do things like this:

```
                state.accountsWithTransactions()?.forEach { item ->
                    val account = item.fragments.mainAccountListItem

                    val models = mutableListOf<EpoxyModel<*>>()

                    models.buildAccountModels(account)

                    if (account.isDefaultAccount) {
                        models.buildExpandedModels(account)
                    }

                    AccountWithTransactions(models).addTo(this)

                    rowSpacer {
                        id("bottom_spacer")
                    }
```

Where we've defined some extension functions on the list of models that generate the models and add them to the list:

```
    private fun MutableList<EpoxyModel<*>>.buildAccountModels(account: MainAccountListItem) {
        val accentColor = getAccentColor(account.type)

        this += AccountAccentLineBindingModel_()
            .id(account.id + "topLine")
            .color(accentColor)

        this += AccountBindingModel_()
            .id(account.id)
            .nickname(account.nickname)
            .balance(account.availableBalance?.let {
                Money(it.amount, it.currency)
            })
            .partialAccountNumber(account.accountNumber?.let {
                AccountNumber(it).partial
            })
            .expanded(account.isDefaultAccount)
            .accountType(account.type.name)
            .iconUrl(account.iconUrl)
            .card(account.cards?.firstOrNull()?.let {
                Card(id = it.id,
                    maskedCardNumber = it.maskedCardNumber,
                    isLocked = it.isLocked,
                    status = CardStatus.valueOf(it.status.rawValue()),
                    shippingInformation = it.shippingInformation?.message?.let { message ->
                        ShippingInformation(message)
                    }
                )
            })
            .status(Status.valueOf(account.status.rawValue()))
            .onClick { _ ->
                findNavController().navigate(
                    AccountsFragmentDirections.actionNavAccountsToNavAccount(account.id)
                )
            }
    }
```

Now it'd be much nicer not to have to use the *BindingModel_() builder pattern, and instead use the Kotlin DSL variant, but I wasn't able to figure out how to make a model with that DSL that wasn't immediately added to an EpoxyController. Is there a way to generate models with the DSL that can be added to a controller later, or added to the list of models inside an `EpoxyModelGroup` directly?

Thanks in advance!

**Comment by elihart** [comment]
Hi there, as you've noticed the generated DSL uses the EpoxyController as a receiver and auto adds itself. And yes, it would be nice to have a tool to create a list using the DSL.

This is possible, it will just take a little Kotlin magic :)

I think something like this would work
```
fun buildModelList(buildModelsBlock: EpoxyController.() -> Unit): List<EpoxyModel<*>> {
    val controller = object : EpoxyController() {
        override fun buildModels() {
            buildModelsBlock()
        }
    }

    controller.requestModelBuild()
    return controller.adapter.copyOfModels
}

// Usage like
val modelList = buildModelList {
    myView {

    }

    otherView {

    }
}
```

The downside is that it is wasteful to create that full EpoxyController just for that list. Not terrible, but gives a slight hit to performance.

It would be nice to have an internal version we provide that is able to do this in a more efficient way.

Pull requests welcome :) In the meantime I think using the above pattern will work fine for you.

**Comment by nealsanche** [comment]
Nice, thanks. I'll give this a try for now, and then see if I have time for a PR.

**Comment by nealsanche** [comment]
@elihart I've had a bit of time to see if I could make what you suggested work. Initially when I use the `buildModelList` function, I get the following exception thrown:

```
    java.lang.IllegalArgumentException: Models cannot be empty
        at com.airbnb.epoxy.EpoxyModelGroup.<init>(EpoxyModelGroup.java:88)
        at com.airbnb.epoxy.EpoxyModelGroup.<init>(EpoxyModelGroup.java:71)
        at com.some.bank.presentation.main.accounts.AccountsFragment$AccountWithTransactions.<init>(AccountsFragment.kt:68)
        at com.some.bank.presentation.main.accounts.AccountsFragment$epoxyController$1.invoke(AccountsFragment.kt:117)
        at com.some.bank.presentation.main.accounts.AccountsFragment$epoxyController$1.invoke(AccountsFragment.kt:37)
        at com.some.bank.presentation.base.MvRxEpoxyControllerKt$simpleController$2$1.invoke(MvRxEpoxyController.kt:48)
        at com.some.bank.presentation.base.MvRxEpoxyControllerKt$simpleController$2$1.invoke(Unknown Source:6)
        at com.airbnb.mvrx.StateContainerKt.withState(StateContainer.kt:6)
        at com.some.bank.presentation.base.MvRxEpoxyControllerKt$simpleController$2.invoke(MvRxEpoxyController.kt:47)
        at com.some.bank.presentation.base.MvRxEpoxyControllerKt$simpleController$2.invoke(Unknown Source:6)
        at com.some.bank.presentation.base.MvRxEpoxyController.buildModels(MvRxEpoxyController.kt:22)
```
It seems like requesting a model build isn't something that happens synchronously, and so the list of models isn't ready in time.

I'll see if I can make this happen synchronously or not.

**Comment by nealsanche** [comment]
I did a little more tracing, and in the debugger it looks like the models all generate normally. Definitely a race condition is existing in this that I'd have to delve deeper than I really want to right now. Will revisit if I have some free time.

**Comment by nealsanche** [comment]
If I disable Async model building in my simpleController, I don't get the exception. Might be the way forward for me, since this screen really doesn't have a lot going on.

**Comment by elihart** [comment]
The first time an EpoxyController has `requestModelBuild` called on it it builds models synchronously, after that it is posted to the handler set on the controller.

So for this case a new EpoxyController would need to be used for each list (until we build this into the library in a way that enables repeat usage synchronously)
