### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by AttITuder** [airbnb/epoxy#831]
I'm using Epoxy version 3.4.2 and I extends Typed2EpoxyController to build my models.
Add model dynamically by sliding down, then crash by sliding up

   Process: com.sinafq.standard, PID: 10979
    java.util.ConcurrentModificationException
        at java.util.AbstractList$SubAbstractList.listIterator(AbstractList.java:314)
        at java.util.AbstractList$SubAbstractList.iterator(AbstractList.java:301)
        at java.util.AbstractList.hashCode(AbstractList.java:525)
        at java.util.Collections$SynchronizedList.hashCode(Collections.java:543)
        at sinainstalment.database.homemodule.viewmodel.Goods_Rec_Model_.hashCode(Goods_Rec_Model_.java:320)
        at com.airbnb.epoxy.EpoxyModel.validateStateHasNotChangedSinceAdded(EpoxyModel.java:460)
        at com.airbnb.epoxy.ControllerHelper.validateModelHashCodesHaveNotChanged(ControllerHelper.java:18)
        at sinainstalment.database.homemodule.viewmodel.controller.ViewModelController2_EpoxyHelper.validateModelsHaveNotChanged(ViewModelController2_EpoxyHelper.java:31)
        at sinainstalment.database.homemodule.viewmodel.controller.ViewModelController2_EpoxyHelper.resetAutoModels(ViewModelController2_EpoxyHelper.java:23)
        at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:263)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)

**Comment by elihart** [comment]
it looks like the list in your `Goods_Rec_Model_` is not thread safe. your model must have immutable data. this isn't an Epoxy issue, it's an issue with your mutable state.
