### ISSUE TITLE
Getting a crash when reusing layouts for different EpoxyModel

### ISSUE THREAD

**Issue by markherscher** [airbnb/epoxy#854]
I have two `EpoxyModelWithHolder`s that I'd like to have use the same layout file. However, I am getting `ClassCastException` at random times; usually when the controller is refreshed again. If I switch the layout file and change nothing else, it works. Is this expected behavior?

A simple example follows.

### First model
```
@EpoxyModelClass(layout = R.layout.test_epoxy_layout)
abstract class TestEpoxyView1 : EpoxyModelWithHolder<TestEpoxyView1.ViewHolder>() {
    class ViewHolder : KotlinEpoxyHolder()
}
```

#### If I change this to point at another layout resource (even an exact duplicate of test_epoxy_layout) it will no longer crash
```
@EpoxyModelClass(layout = R.layout.test_epoxy_layout)
abstract class TestEpoxyView2 : EpoxyModelWithHolder<TestEpoxyView2.ViewHolder>() {
  class ViewHolder : KotlinEpoxyHolder()
}
```

### Layout file test_epoxy_layout
```
<?xml version="1.0" encoding="utf-8"?>
<View xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="1dp"
  android:background="#FFFFFF" />
```

### Inside Controller.buildModels()
```
    testEpoxyView1 { id(UUID.randomUUID().toString()) }
    testEpoxyView2 { id(UUID.randomUUID().toString()) }
```

The following exception is thrown the second time the controller is updated.

```   
 java.lang.ClassCastException: xxxx.TestEpoxyView2$ViewHolder cannot be cast to xxxx.TestEpoxyView1$ViewHolder
        at xxxx.TestEpoxyView1_.handlePreBind(TestEpoxyView1_.java:22)
        at com.airbnb.epoxy.EpoxyViewHolder.bind(EpoxyViewHolder.java:53)
        at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:98)
        at com.airbnb.epoxy.BaseEpoxyAdapter.onBindViewHolder(BaseEpoxyAdapter.java:15)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1888)
        at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:407)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by elihart** [comment]
Can you paste the full stacktrace? the important part with the exception message is missing.

also i know this may be for example, but never use `randomUUID` or any other random data in a model id.

**Comment by markherscher** [comment]
Oops, I messed up the formatting. I fixed it now.

I have heard about that for the ID, but this was existing code. If it was changed over, though, would that fix this issue? My understanding is no.

**Comment by elihart** [comment]
Ok, so yes this is because two different view holder classes have the same layout id, and this is expected.

Look at the handlePreBind method in the error trace
```
void handlePreBind(EpoxyViewHolder holder, T objectToBind, int position)
```

The object to bind here is the view holder. If you simply pull `class ViewHolder : KotlinEpoxyHolder()` out to a standalone class instead of nesting it in each epoxy model then it should work fine to share them. remember that for `EpoxyModelWithHolder` it is typed based on the view holder, not on the View.

The random id won't cause a crash, but will completely mess up your animations and diffing, and will be less efficient because it will rebind everything on each change

**Comment by markherscher** [comment]
I did try that, but it still crashed. We originally did have it separated as well. For clarity, I changed both classes to be this:

```
@EpoxyModelClass(layout = R.layout.test_epoxy_layout)
abstract class TestEpoxyView1 : EpoxyModelWithHolder<TestViewHolder1>()

class TestViewHolder1 : KotlinEpoxyHolder()
```

```
@EpoxyModelClass(layout = R.layout.test_epoxy_layout)
abstract class TestEpoxyView2 : EpoxyModelWithHolder<TestViewHolder2>()

class TestViewHolder2 : KotlinEpoxyHolder()
```

**Comment by elihart** [comment]
You're not using the same class though - one model uses `TestViewHolder1` and the other uses `TestViewHolder2`. they need to use the same one!

**Comment by elihart** [comment]
Yes, they need to use the same viewholder. A viewholder goes one to one with a layout, so why not reuse the viewholder anway to save code?

**Comment by markherscher** [comment]
Is it documented somewhere that two or more view holders cannot use the same layout resource?

I won't go into the boring details but basically we wanted to reuse a layout file but didn't need to reuse the view holder. We certainly can, but we were surprised by the crash.

**Comment by baoti** [comment]
You can share the Holder Class or use a layout resource alias in ViewModel2.

**Comment by elihart** [comment]
I guess it's not documented

**Comment by markherscher** [comment]
Thank you for your help!
