### ISSUE TITLE
Can we add Paris's @Stylable to an EpoxyModelWithHolder class ?

### ISSUE THREAD

**Issue by eboudrant** [airbnb/epoxy#878]
We use the models with holder pattern in some or our codebase. I was wondering if Paris support this pattern.

```
@Styleable
@EpoxyModelClass
abstract class OurModel : EpoxyModelWithHolder<OurModel.Holder>() { ... }
```

Will fail on

```
e: [kapt] An exception occurred: kotlin.TypeCastException: null cannot be cast to non-null type javax.lang.model.element.TypeElement
	at com.airbnb.paris.processor.framework.WithSkyProcessor$DefaultImpls.asTypeElement(WithSkyProcessor.kt:45)
	at com.airbnb.paris.processor.WithParisProcessor$DefaultImpls.asTypeElement(WithParisProcessor.kt)
	at com.airbnb.paris.processor.StyleablesTree.asTypeElement(StyleablesTree.kt:7)
	at com.airbnb.paris.processor.StyleablesTree.findStyleApplier$paris_processor(StyleablesTree.kt:32)
	at com.airbnb.paris.processor.StyleablesTree.findStyleApplier$paris_processor(StyleablesTree.kt:32)
	at com.airbnb.paris.processor.StyleablesTree.findStyleApplier$paris_processor(StyleablesTree.kt:32)
	at com.airbnb.paris.processor.writers.StyleApplierJavaClass$block$1.invoke(StyleApplierJavaClass.kt:43)
	at com.airbnb.paris.processor.writers.StyleApplierJavaClass$block$1.invoke(StyleApplierJavaClass.kt:8)
	at com.airbnb.paris.processor.framework.SkyJavaClass.build(SkyJavaClass.kt:14)
	at com.airbnb.paris.processor.framework.SkyJavaClass.write(SkyJavaClass.kt:19)
	at com.airbnb.paris.processor.ParisProcessor.processRound(ParisProcessor.kt:115)
	at com.airbnb.paris.processor.framework.SkyProcessor.process(SkyProcessor.kt:32)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
```

**Comment by elihart** [comment]
To be clear, you want the generated model to behave similarly to @ModelView generated models that use Paris?
1. Instantiate the view directly instead of inflating from layout
2. Include functions on the generated model to set the style with Paris

I'm wondering about the first one - since a view holder is being used it needs a layout to be provided. Where would you want to provide this? One idea is to use a special type of view holder that defines the layout file and indicates to Epoxy that it should generate the model with Paris support.

I don't know that using the `@Styleable` annotation on the model should be supported. This should fail in Paris since only Views can be annotated with this - I would like to avoid Paris needing to know about Epoxy models.

Maybe instead `EpoxyModelClass` can have a parameter for whether Paris should be supported (a big ugly to tie the libraries together that way)? Or Epoxy could provide a @StyleableEpoxyModel annotation

**Comment by eboudrant** [comment]
Yes, sorry, I had a bad understanding of the `@Styleable` annotation. As you mention it has no Epoxy knowledge.

I think we can close this issue unless there is a real interest in implementing what you are proposing.

**Comment by elihart** [comment]
Ok, sounds good.

**Comment by Dwite** [comment]
@elihart I'm kinda curious how to properly add possibility of styling using `Paris` for `EpoxyModelWithHolder`. Currently I'm trying something like:

```
@EpoxyModelClass(layout = R.layout.component_header)
abstract class HeaderEpoxyModel : ViewBindingEpoxyModelWithHolder<ComponentHeaderBinding>() {
    @EpoxyAttribute(EpoxyAttribute.Option.DoNotHash) var clickListener: View.OnClickListener? = null
    @EpoxyAttribute lateinit var title: String
    @EpoxyAttribute var styleBuilder: (ExtendableStyleBuilder<View>.() -> Unit)? = null

    override fun ComponentHeaderBinding.bind() {
        headerTextView.apply {
            text = title
            clickListener?.let { clickListener -> setOnClickListener { clickListener.onClick(this) } }
        }

        styleBuilder?.let { root.style(it) }
    }
}
```

And from outside it will be used like

```
header {
            id("start return header")
            title(getString(R.string.returns_start_header))
            styleBuilder { it.layoutMarginBottomDp(36) }
        }
```

But it feels I'm missing some obvious simple solution to do that?
