### ISSUE TITLE
IndexOutOfBoundsException: PagedListModelCache.getModels()

### ISSUE THREAD

**Issue by grosalex** [airbnb/epoxy#913]
Hey,
First of all thanks for epoxy it's amazing. 
I'm filling out this issue cause recently we have a new crash in production I'm deeply sorry I didn't manage to reproduce it I was wondering if you knew what can cause this or else?
here is the stacktrace : 
`Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 50, Size: 50
       at androidx.paging.PagedStorage.get(PagedStorage.java:138)
       at androidx.paging.PagedList.get(PagedList.java:633)
       at com.airbnb.epoxy.paging.PagedListModelCache.getModels(PagedListModelCache.kt:200)
       at com.airbnb.epoxy.paging.PagedListEpoxyController.buildModels(PagedListEpoxyController.kt:74)
       at com.airbnb.epoxy.EpoxyController$1.run(EpoxyController.java:276)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

It's mostly working well but it seems to appear sometimes. It can happen on all sort and brand devices and on all android version.

I don't have so much more infos to give you, but I'm at your disposal if have questions or else.

regards,

**Comment by grosalex** [comment]
Find out what was the cause of this error.
We were having a buggy changing items' order hapenning wich was causing this.

Sorry for the issue, closing it.

Regards,

**Comment by mabuthraa** [comment]
> Find out what was the cause of this error.
> We were having a buggy changing items' order hapenning wich was causing this.
> 
> Sorry for the issue, closing it.
> 
> Regards,

@grosalex  we got same issue .. will it be fixed in the release 3.10 ? 
thanks
