### ISSUE TITLE
App crashes when sticky header is not the first item in the list

### ISSUE THREAD

**Issue by dleonett** [airbnb/epoxy#974]
Hello team, I'm trying to implement this Sticky Headers newly added feature and I'm getting a crash when the item I want as sticky is not the first element in the list.

Let's say my list has following structure (not working):

```
[0] Header
[1] ItemHeader (sticky)
[2] ItemDetail
[3] ItemHeader (sticky)
[4] ItemDetail
[5] ItemHeader (sticky)
[6] ItemDetail
[7] Footer
```

But if I set it as follows app works without any issues:

```
[0] Header (sticky)
[1] ItemHeader (sticky)
[2] ItemDetail
[3] ItemHeader (sticky)
[4] ItemDetail
[5] ItemHeader (sticky)
[6] ItemDetail
[7] Footer
```

Is this a known issue/limitation?
Thank you guys!

**Comment by dleonett** [comment]
Logs:

```
2020-05-16 22:43:09.610 10605-10605/com.leonett.epoxysample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.leonett.epoxysample, PID: 10605
    java.lang.ArrayIndexOutOfBoundsException: length=25; index=-1
        at java.util.ArrayList.get(ArrayList.java:413)
        at java.util.Collections$UnmodifiableList.get(Collections.java:1295)
        at com.airbnb.epoxy.BaseEpoxyAdapter.getModelForPosition(BaseEpoxyAdapter.java:171)
        at com.airbnb.epoxy.BaseEpoxyAdapter.getItemViewType(BaseEpoxyAdapter.java:159)
        at com.airbnb.epoxy.stickyheader.StickyHeaderLinearLayoutManager.updateStickyHeader(StickyHeaderLinearLayoutManager.kt:237)
        at com.airbnb.epoxy.stickyheader.StickyHeaderLinearLayoutManager.onLayoutChildren(StickyHeaderLinearLayoutManager.kt:111)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
        at android.view.View.layout(View.java:17637)
        at android.view.ViewGroup.layout(ViewGroup.java:5575)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by dleonett** [comment]
### Possible fix

In `StickyHeaderLinearLayoutManager.updateStickyHeader()` method, check that `headerPos != -1` before trying to call `getItemViewType(headerPos)` so we prevent the `ArrayIndexOutOfBoundsException`.

```kotlin
if (headerPos != -1) {
    val itemViewType = adapter?.getItemViewType(headerPos) ?: -1
```

**Comment by dleonett** [comment]
### Temporary workaround

1. Copy `StickyHeaderLinearLayoutManager` class into your base code and use that one when instantiating the layout manager.
2. In that new class move line `237`:
```kotlin
val itemViewType = adapter?.getItemViewType(headerPos) ?: -1
```
and place it right after this validation:
```kotlin
if (headerPos != -1 &&
    (headerPos != anchorPos || isViewOnBoundary(anchorView)) &&
    nextHeaderPos != headerPos + 1) {
```

**Comment by elihart** [comment]
@AkshayChordiya can you help with this?

**Comment by AkshayChordiya** [comment]
The fix which @dleonett mentioned should fix the problem. I'll try it out tomorrow and create a PR 🙏🏻
Unless @madicap wants to create a PR 😊

**Comment by AkshayChordiya** [comment]
@dleonett I tried to reproduce the scenario which you mentioned but I didn't see any crash without fixing anything [not sure if footer made a difference 🤔 ]
```
[0] Header (sticky)
[1] ItemHeader (sticky)
[2] ItemDetail
[3] ItemHeader (sticky)
[4] ItemDetail
[5] ItemHeader (sticky)
[6] ItemDetail
```

But moving `adapter?.getItemViewType(headerPos) ?: -1` inside the `if` block does make sense so I'll create a PR with the fix.

**Comment by AkshayChordiya** [comment]
@elihart I have tested this and created the PR with the fix as @dleonett pointed out. Hoping we can release the fix soon :)

**Comment by elihart** [comment]
thanks for the quick fix, will try to get a release out soon

**Comment by dleonett** [comment]
Thank you guys! @AkshayChordiya @elihart
